spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 84746913795-k30oubqg1dpgkrb1f55hfbb4g989pp8d.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: O7DME20DgdPhXVbbfCtA
            client-secret: kNNwyRLa7S
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 7096fe44c0159c935861456195252207
            client-secret: edajf0LRXV6GIYjtTAxssqibjy6H4hJb
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버 로그인 창을 받을수 있다
            token-uri: https://nid.naver.com/oauth2.0/token #토큰을 받는 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 주소를 받는 uri
            user-name-attribute: response #회원 벙보를 json 형태로 받는데 response 라는 키값으로 네이버가 리턴해줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id